name = "TSWebDev"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A minimalist, professional web developer portfolio theme."
tags = ["portfolio", "minimal", "developer"]
author = "TSWebDev"
